#spring:
#  application:
#    name: licensing-service
#  profiles:
#    active: dev
#  config:
#    import: optional:configserver:http://configserver:8071
#  cloud:
#    config:
#      name: licensing-service-dev
#      active: dev
#
#  main:
#    allow-bean-definition-overriding: true