#
#spring:
#  application:
#    name: config-server
#  profiles:
#    active: git #native, git, vault
#  cloud:
#    config:
#      server:
#        #        #복호화 기능이다
#        #        encrypt:
#        #          enabled: false
##        native:
##          # classpath를 사용하면 src/main/resources/config 폴더를 찾는다
##          search-locations: classpath:/config
#        git:
#          uri: https://github.com/klimtever/config.git
#          defaultLabel: master
#          searchPaths: licensingservice
##        vault:
##          port: 8200
##          host: 127.0.0.1
##          kvVersion: 2
##          profile-separator: /
##          backend: licensing-service
#server:
#  port: 8071
#
## 암호화에 사용할 키
#encrypt:
#  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo
#
##Enable all Spring Boot Actuator endpoints.
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"