version: '2.1'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_TOKEN=myroot
    networks:
      backend:
        aliases:
          - "vault"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/file:/vault/data
      - ./vault/vault-init.sh:/vault/vault-init.sh
    cap_add:
      - IPC_LOCK
    command: ["sh", "/vault/vault-init.sh"]
    healthcheck:
      test: ["CMD", "vault", "status", "-address=http://127.0.0.1:8200"]
      interval: 5s
      timeout: 5s
      retries: 10

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  configserver:
    image: intheeast0305/configserver:1.0.0
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
      VAULT_HOST: "vault"
    depends_on:
      vault:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "configserver"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 15

  licensingservice:
    image: intheeast0305/licensing-service:1.0.0
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT: "8071"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge